### ISSUE TITLE
Where's the initial files? 

### ISSUE THREAD

**Issue by Rellotscrewdriver** [BeegCat/hello_world#2]
I see that you uploaded only readme.md, and not the the files like .cpp or .c

**Comment by BeegCat** [comment]
> I see that you uploaded only readme.md, and not the the files like .cpp or .c

Good obssrvation. Actually I'm new to github so I'm trying to get hold on the stuffs here. Codes on their way!! Thank you.

**Comment by Rellotscrewdriver** [comment]
you do know that you can close this issue :stonks:
